---
version: 2.1

executors:
  go_1_14_img:
    docker:
      - image: cimg/go:1.14

build-template: &build-template
  environment:
    # path to where test results will be saved
    TEST_RESULTS: /tmp/test-results

  steps:
    - checkout
    # create the test results directory
    - run: mkdir -p $TEST_RESULTS
    # restores saved cache if no changes are detected since last run
    - restore_cache:
        keys:
          - cimg-go-pkg-mod-{{ checksum "go.sum" }}
    - run:
        name: "Linter and Test Coverage Report"
        command: |
          make ci
          mv coverage.* $TEST_RESULTS/

    - save_cache:
        key: cimg-go-pkg-mod-{{ checksum "go.sum" }}
        paths:
          - "/home/circleci/go/pkg/mod"

    - store_artifacts:
        path: /tmp/test-results
        destination: pk60-go-test-output

    - store_test_results:
        path: /tmp/test-results

    - run:
        name: "Upload Test Coverage Report"
        command: |
          curl -s https://codecov.io/bash | \
          bash -s -- -f $TEST_RESULTS/coverage.txt -Z || \
          echo 'Codecov upload failed'

jobs:
  go_1_14_job:
    executor: go_1_14_img
    <<: *build-template

workflows:
  version: 2
  build:
    jobs:
      - go_1_14_job
